Remove a surplus ie_len to avoid compiling error
When I compiled rtl8188eus under Ubuntu=14.04 and kernel version=3.13.0, I got this error: 
.../rtl8188eus/os_dep/linux/ioctl_cfg80211.c:1224:4: error: too many arguments to function ‘cfg80211_disconnected’
    rtw_cfg80211_disconnected(pwdev, reason, NULL, 0, locally_generated, GFP_ATOMIC);
I found the function declaration line 366-369 in this file. When kernel version < 4.2.0 and undefine RHEL79, just as my condition,  
#define rtw_cfg80211_disconnected(wdev, reason, ie, ie_len, locally_generated, gfp) cfg80211_disconnected(wdev_to_ndev(wdev), reason, ie, ie_len, ie_len, gfp)
Looking up from https://elixir.bootlin.com/linux/, indeed, cfg80211_disconnected add a locally_generated parameter after 4.2.0-rc1. While before 4.1.52, it only had 5 parameters: void cfg80211_disconnected(struct net_device *dev, u16 reason, const u8 *ie, size_t ie_len, gfp_t gfp);
By comparing, I thought the surplus ie_len should be removed in line 366.
My compilation passed.